/* FILE AUTOMATICALLY GENERATED BY: /utils/lookup_table_gen.py */

#ifndef LIB_LOOKUP_TABLES_H_INCLUDED
#define LIB_LOOKUP_TABLES_H_INCLUDED

#include <stdint.h>

// the sine LUT, range: [0, 4094], centered around 2047
extern const uint16_t SINE_LUT[1024];

// the exponential mapping LUT, range: [33, 50000], units: millihertz
extern const uint16_t EXPO_MAPPING_LUT_mHz[1024];

#endif