/* FILE AUTOMATICALLY GENERATED BY: /utils/lookup_table_gen.py */

#ifndef LIB_LOOKUP_TABLES_H_INCLUDED
#define LIB_LOOKUP_TABLES_H_INCLUDED

#include <stdint.h>

// the sine LUT, range: [0, 4094]
extern const uint16_t SINE_LUT[1024];

// the exponential mapping LUT, range: [0.03333333333333333, 50.0]
extern const float EXPO_MAPPING_LUT[1024];

#endif